module.exports = {
  extends: ['gitmoji'],
  rules: {
    'header-max-length': [2, 'always', 300],
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'upgrade',
        'fix',
        'hotfix',
        'types',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
        'merge',
        'text',
        'wip',
        'config',
        'setup',
        'i18n',
        'deploy',
        'improve',
        'database',
      ],
    ],
  },
};
