/**
 * Mapping direct des noms de pays du GeoJSON vers les codes ISO-2
 * Cela permet d'associer les noms de pays utilisés dans le fichier de géographie
 * avec les codes ISO-2 standards utilisés dans notre base de données
 */
export const countryNameToIsoMap: Record<string, string> = {
  // Europe
  France: 'FR',
  Germany: 'DE',
  'United Kingdom': 'GB',
  Italy: 'IT',
  Spain: 'ES',
  Belgium: 'BE',
  Netherlands: 'NL',
  Switzerland: 'CH',
  Poland: 'PL',
  Ireland: 'IE',
  Portugal: 'PT',
  Sweden: 'SE',
  Norway: 'NO',
  Finland: 'FI',
  Denmark: 'DK',
  Austria: 'AT',
  Greece: 'GR',
  Luxembourg: 'LU',
  Hungary: 'HU',
  'Czech Rep.': 'CZ',
  Romania: 'RO',
  Bulgaria: 'BG',
  Slovakia: 'SK',
  Slovenia: 'SI',
  Estonia: 'EE',
  Latvia: 'LV',
  Lithuania: 'LT',
  Croatia: 'HR',
  Malta: 'MT',
  Cyprus: 'CY',
  Iceland: 'IS',
  Montenegro: 'ME',
  Serbia: 'RS',
  'Bosnia and Herz.': 'BA',
  Albania: 'AL',
  Macedonia: 'MK',
  Moldova: 'MD',
  Ukraine: 'UA',
  Belarus: 'BY',
  Russia: 'RU',

  // Afrique
  Morocco: 'MA',
  Algeria: 'DZ',
  Tunisia: 'TN',
  Libya: 'LY',
  Egypt: 'EG',
  Senegal: 'SN',
  Mali: 'ML',
  Mauritania: 'MR',
  Niger: 'NE',
  Nigeria: 'NG',
  Chad: 'TD',
  Sudan: 'SD',
  'S. Sudan': 'SS',
  Eritrea: 'ER',
  Ethiopia: 'ET',
  Djibouti: 'DJ',
  Somalia: 'SO',
  Kenya: 'KE',
  Tanzania: 'TZ',
  Uganda: 'UG',
  Rwanda: 'RW',
  Burundi: 'BI',
  'Dem. Rep. Congo': 'CD',
  Congo: 'CG',
  Angola: 'AO',
  Zambia: 'ZM',
  Malawi: 'MW',
  Mozambique: 'MZ',
  Zimbabwe: 'ZW',
  Botswana: 'BW',
  Namibia: 'NA',
  'South Africa': 'ZA',
  Eswatini: 'SZ',
  Lesotho: 'LS',
  Madagascar: 'MG',
  Comoros: 'KM',
  Mauritius: 'MU',
  Cameroon: 'CM',
  Gabon: 'GA',
  'Equatorial Guinea': 'GQ',
  'Ivory Coast': 'CI',
  'Burkina Faso': 'BF',
  Ghana: 'GH',
  Togo: 'TG',
  Benin: 'BJ',
  Guinea: 'GN',
  'Guinea-Bissau': 'GW',
  'Sierra Leone': 'SL',
  Liberia: 'LR',
  Gambia: 'GM',
  'Central African Rep.': 'CF',

  // Amériques
  'United States of America': 'US',
  Canada: 'CA',
  Mexico: 'MX',
  Guatemala: 'GT',
  Belize: 'BZ',
  'El Salvador': 'SV',
  Honduras: 'HN',
  Nicaragua: 'NI',
  'Costa Rica': 'CR',
  Panama: 'PA',
  Colombia: 'CO',
  Venezuela: 'VE',
  Ecuador: 'EC',
  Peru: 'PE',
  Brazil: 'BR',
  Bolivia: 'BO',
  Paraguay: 'PY',
  Chile: 'CL',
  Argentina: 'AR',
  Uruguay: 'UY',
  Cuba: 'CU',
  Haiti: 'HT',
  'Dominican Rep.': 'DO',
  Jamaica: 'JM',
  'Trinidad and Tobago': 'TT',
  Bahamas: 'BS',
  Guyana: 'GY',
  Suriname: 'SR',

  // Asie
  China: 'CN',
  India: 'IN',
  Pakistan: 'PK',
  Afghanistan: 'AF',
  Iran: 'IR',
  Iraq: 'IQ',
  'Saudi Arabia': 'SA',
  Kuwait: 'KW',
  Qatar: 'QA',
  'United Arab Emirates': 'AE',
  Oman: 'OM',
  Yemen: 'YE',
  Syria: 'SY',
  Jordan: 'JO',
  Lebanon: 'LB',
  Israel: 'IL',
  Palestine: 'PS',
  Turkey: 'TR',
  Georgia: 'GE',
  Armenia: 'AM',
  Azerbaijan: 'AZ',
  Turkmenistan: 'TM',
  Uzbekistan: 'UZ',
  Kazakhstan: 'KZ',
  Kyrgyzstan: 'KG',
  Tajikistan: 'TJ',
  Mongolia: 'MN',
  Nepal: 'NP',
  Bhutan: 'BT',
  Bangladesh: 'BD',
  'Sri Lanka': 'LK',
  Japan: 'JP',
  'South Korea': 'KR',
  'North Korea': 'KP',
  Vietnam: 'VN',
  Cambodia: 'KH',
  Laos: 'LA',
  Myanmar: 'MM',
  Thailand: 'TH',
  Malaysia: 'MY',
  Singapore: 'SG',
  Indonesia: 'ID',
  Philippines: 'PH',
  Brunei: 'BN',
  Taiwan: 'TW',

  // Océanie
  Australia: 'AU',
  'New Zealand': 'NZ',
  'Papua New Guinea': 'PG',
  Fiji: 'FJ',
  'Solomon Is.': 'SB',
  Vanuatu: 'VU',
  'New Caledonia': 'NC',
};
